### PR TITLE
Use random private key if there is no secret provided

### LINKED ISSUE #49: Error while running the app
I get this error, when ever i try to run `yarn dev`

```bash
snapshot-sidekick/node_modules/@ethersproject/bytes/src.ts/index.ts:58
    return !!(value.toHexString);
                    ^
TypeError: Cannot read properties of undefined (reading 'toHexString')
```

### PR DESCRIPTION
**Pull request by ChaituVR**
Fixes #49 

Also fixed few lint

### CODE REVIEW

**Review by wa0x6e — COMMENTED** [review]
Do we really want to fallback to random PRIVATE_KEY on each start ? 

The key does appear in `.env.example`, and should be required for initial setup, to get consistent result, on dev and testing.

Setting a fallback may hide the fact that the key was not properly set up. Isn't it better to check for key presence, and throw an error with a message "WALLET_PRIVATE_KEY is missing" when missing, like for the AWS credentials ?

**Comment by ChaituVR** [comment]
WALLET_PRIVATE_KEY Is a mandatory env to run sidekick?

**Comment by wa0x6e** [comment]
> WALLET_PRIVATE_KEY Is a mandatory env to run sidekick?

Everything in .env is mandatory, and should raise an error when misconfigured

**Comment by wa0x6e** [comment]
I get the feeling you're getting this error after pulling from the `main`, and not from a new setup, in which case it's normal to wonder why it stopped working, due to lack of changelog.

**Comment by ChaituVR** [comment]
> Everything in .env is mandatory, and should raise an error when misconfigured

Cool then I will leave it to you then, can close this PR

**Pull request closed without merging**
