### PR TITLE
Change default port

### PR DESCRIPTION
**Pull request by ChaituVR**
- While development/testing other repo's ports are conflicting, better to use unique one, ports upto 3004 are already in use :) 
- Also better to move this to the `master` branch like other repos @wa0x6e @bonustrack you have permission to change it? 
- Or we should change all other to `main` :)

### CODE REVIEW

**Comment by wa0x6e** [comment]
Some repos are on `main`, such as https://github.com/snapshot-labs/envelop and https://github.com/snapshot-labs/envelop-ui

**Comment by bonustrack** [comment]
I'd rather move all to `main`, this is the new standard

**Comment by ChaituVR** [comment]
Cool @wa0x6e Lets merge this anyway

**Comment by wa0x6e** [comment]
> Cool @wa0x6e Lets merge this anyway

Still a review pending, see above

**Comment by ChaituVR** [comment]
What's pending? 🤔 I don't see any changes requested 😅 this repo is already on the main branch

**Comment by wa0x6e** [comment]
Something about the default port for the test suite

https://github.com/snapshot-labs/snapshot-sidekick/pull/26/files/eb41709f7ec45bb2c42f9b8438c86401e508a9e3#diff-c3386ce3a7ed60e4d4285ce0ad144092de50798c321b3fb0fd76c2c9dc24cd52R3

**Review by wa0x6e — CHANGES_REQUESTED** [review]
The default PORT should be different than the one on yarn dev, to avoid port already in use error, when launching the tests, while yarn dev is already running.

This PORT number should already be in sync with the one defined in test:e2e command in package.json

**Review by wa0x6e — APPROVED** [review]

**Pull request merged**
